version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: decidim_staperpetua_development
      POSTGRES_USER: decidim_app
      POSTGRES_PASSWORD: decidim

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: decidim_app
      DATABASE_PASSWORD: decidim
      DATABASE_NAME: decidim_staperpetua_development
      RAILS_ENV: development

volumes:
  postgres_data:
